### ISSUE TITLE
Ansible 2.0 compatible

### ISSUE THREAD

**Issue by drzraf** [sbitio/ansible-munin#14]
```
ERROR! Unexpected Exception: No module named template
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 86, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 140, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 238, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/strategy/linear.py", line 202, in run
    action = action_loader.get(task.action, class_only=True)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 326, in get
    self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 313, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/home/dev/ansible/roles/sbitmedia.munin/action_plugins/munin_plugin.py", line 3, in <module>
    from ansible.utils.template import template
ImportError: No module named template
```
``ansible.runner.return_data`` is affected too.

See https://github.com/ansible/ansible/blob/devel/docsite/rst/developing_api.rst

**Comment by drzraf** [comment]
Got this one too:
```
TASK [sbitmedia.munin : Ensure munin.conf] *************************************
task path: /roles/sbitmedia.munin/tasks/config.yml:2
skipping: [vmx] => (item=/roles/sbitmedia.munin/templates/munin.conf.default.j2)  => {"changed": false, "item": "/roles/sbitmedia.munin/templates/munin.conf.default.j2", "skip_reason": "Conditional check failed", "skipped": true}
ERROR! Unexpected Exception: 'bool' object has no attribute 'split'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 86, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 140, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 238, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/strategy/linear.py", line 229, in run
    task_vars = self._variable_manager.get_vars(loader=self._loader, play=iterator._play, host=host, task=task)
  File "/usr/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 341, in get_vars
    all_vars['ansible_delegated_vars'] = self._get_delegated_vars(loader, play, task, all_vars)
  File "/usr/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 479, in _get_delegated_vars
    include_hostvars=False,
  File "/usr/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 245, in get_vars
    all_vars = combine_vars(all_vars, host.get_vars())
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/host.py", line 129, in get_vars
    results['inventory_hostname_short'] = self.name.split('.')[0]
AttributeError: 'bool' object has no attribute 'split'
```

Related? https://github.com/ansible/ansible/issues/1419

**Comment by jonhattan** [comment]
Hi @drzraf sorry I've no plans to work with Ansible 2.0 in the near future. That said, I'll do my best to review and accept any PRs.

**Comment by drzraf** [comment]
thank you for the clarification.

**Comment by jonhattan** [comment]
Hi @drzraf. We quit using ansible to manage services, and we we're not supporting any more our ansible roles. I suggest you fork this role and publish the forked version to the galaxy. If you decide so, we'll add a link to your fork at the top of README.md

**Comment by jonhattan** [comment]
Also, thanks for your efforts in using and making this role better. I'm glad you liked our hacky action_plugins approach :)
